name: EnchantmentHelper
version: '0.11'
description: 'This plugin will help you enchant your stuff quicker!'
main: me.firedroide.plugins.EnchantmentHelper.EnchantmentHelper
load: POSTWORLD
author: 'Firedroide'
database: false
commands:
  enchantinglevel:
    description: Set the level you want to do an enchantment of.
    usage: 'Usage: /<command> level OR /<command> minlevel maxlevel.'
    aliases: [enchantmentlevel, enchantlevel, level, lvl]
