name: EnchantmentHelper
version: '0.12'
description: 'This plugin will help you enchant your stuff quicker!'
main: me.firedroide.plugins.EnchantmentHelper.EnchantmentHelper
load: POSTWORLD
author: 'Firedroide'
database: false
commands:
  enchantinglevel:
    description: Set the level you want to do an enchantment of.
    usage: 'Usage: /<command> level OR /<command> minlevel maxlevel.'
    aliases: [enchantmentlevel, enchantlevel, level, lvl]
permissions:
  enchantmenthelper.use:
    description: Allows people to use EnchantmentHelper.
    default: true
